[package]
name = "steam-backlog-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.19"
dotenv = "0.15.0"
ratatui = "0.29.0"
reqwest = { version = "0.12.26", features = ["json"] }
serde_json = "1.0.145"
serde_toml = "0.0.1"
tokio = "1.48.0"
